server:
  port: 8080 

file:
  path: "/uploads/"

vapid:
  publicKey: "BOG6hM6..." 
  privateKey: "hJL3xLQ..." 
  subject: "mailto:your-email@example.com"  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dalgrak 
    username: root 
    password: rootpw 
  jpa:
    hibernate:
      ddl-auto: update  # JPA DDL 자동 설정
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 
